[build]
  publish = "site"
  functions = "functions"

[functions]
  directory = "functions"

[[redirects]]
  from = "/post/*"
  to = "/.netlify/functions/post"
  status = 200
  force = false
  querty = { lang = ":lang" }

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[functions.post]
    included_files = ["post/*.md"]

[dev]
  autoLaunch = false
