[functions]
  directory = "functions"

[[redirects]]
  from = "/post/*"
  to = "/.netlify/functions/post"
  status = 200
  force = false
  querty = { lang = ":lang" }

[functions.post]
    included_files = ["post/*.md"]
